# Generated by Django 3.0.3 on 2020-02-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='detalle',
            field=models.CharField(default='', max_length=200, verbose_name='Detalle Foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageimage',
            name='titulo',
            field=models.CharField(default='', max_length=200, verbose_name='Título Foto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título Página'),
        ),
    ]
