# Generated by Django 3.0.3 on 2020-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200207_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='posicion',
            field=models.CharField(choices=[('antes', 'Antes'), ('despues', 'Después')], default='', max_length=10, verbose_name='Posición Foto'),
            preserve_default=False,
        ),
    ]
