# Generated by Django 3.0.3 on 2020-02-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200207_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Grupo Páginas')),
            ],
            options={
                'verbose_name': 'Grupo Página',
                'verbose_name_plural': 'Grupos Páginas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='pages.GrupoPage'),
            preserve_default=False,
        ),
    ]
