# Generated by Django 3.0.3 on 2020-02-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200207_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='grupo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='pages.GrupoPage'),
        ),
    ]
