# Generated by Django 3.0.3 on 2020-02-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200207_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopage',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
