# Generated by Django 3.0.4 on 2020-05-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imag/'),
        ),
    ]
