# Generated by Django 3.0.4 on 2020-05-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200502_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/'),
        ),
    ]
