# Generated by Django 3.0.4 on 2020-05-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200502_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('caracteristicas', models.CharField(max_length=600, verbose_name='Caractrísticas')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Grupo Técnico',
                'verbose_name_plural': 'Grupos Técnicos',
                'ordering': ['order', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ListaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Descripción')),
                ('proceso', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Proceso')),
                ('cirugia', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='Cirugia')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img/')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_tecnico', to='pages.GrupoTecnico')),
            ],
        ),
    ]
