# Generated by Django 3.0.4 on 2020-05-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_grupotecnico_listatecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupotecnico',
            name='caracteristicas',
            field=models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='Caractrísticas'),
        ),
    ]
