# Generated by Django 3.0.4 on 2020-05-14 15:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200514_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupotecnico',
            name='caracteristicas',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
