# Generated by Django 3.0.4 on 2020-05-14 15:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200514_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupotecnico',
            name='caracteristicas',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Contenido'),
        ),
    ]
