# Generated by Django 3.0.4 on 2020-05-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200514_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listatecnica',
            name='uso',
            field=models.PositiveIntegerField(default=1, verbose_name='Uso'),
        ),
    ]
