# Generated by Django 3.0.4 on 2020-04-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='idciudad',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Código Ciudad'),
        ),
    ]
