# Generated by Django 3.0.4 on 2020-04-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200405_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eps',
            name='created',
        ),
        migrations.RemoveField(
            model_name='eps',
            name='updated',
        ),
    ]
