# Generated by Django 3.0.4 on 2020-04-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20200411_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddetalle',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_detalle', to='pedidos.Solicitud'),
        ),
    ]
