# Generated by Django 3.0.4 on 2020-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20200412_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_cirugia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cirugía (dd/mm/aa)'),
        ),
    ]
