# Generated by Django 3.0.4 on 2020-04-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20200413_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='tipo_ter',
            field=models.CharField(blank=True, choices=[('Paciente', 'Paciente'), ('Hospital', 'Hospital'), ('Medico', 'Medico'), ('Pagador', 'Pagador')], default='', max_length=10, null=True, verbose_name='Tipo Tercero'),
        ),
    ]
