# Generated by Django 3.0.4 on 2020-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20200421_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='Fecha de Nacimiento DD/MM/AAAA'),
        ),
    ]
