# Generated by Django 3.0.4 on 2020-05-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20200423_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='idciudad',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Código Ciudad'),
        ),
        migrations.AlterField(
            model_name='ciudaddireccion',
            name='idciudad',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Código Ciudad'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='iddepartamento',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Código Departamento'),
        ),
        migrations.AlterField(
            model_name='eps',
            name='ideps',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='idespecial',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Código Especialidad'),
        ),
        migrations.AlterField(
            model_name='especialidadinjerto',
            name='idespecial',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Código Especialidad'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idgrupo',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Código Grupo'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='idpais',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Código País'),
        ),
        migrations.AlterField(
            model_name='plansalud',
            name='idplan',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Código Plan'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='direccion_envio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dirección de Envio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono_envio',
            field=models.CharField(blank=True, default='', max_length=35, verbose_name='Teléfono de Envio'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='apel1',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='apel2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='ciudad_direccion',
            field=models.ForeignKey(blank=True, default='', max_length=5, on_delete=django.db.models.deletion.CASCADE, to='pedidos.CiudadDireccion', verbose_name='Ciudad Direcciòn'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='identificacion',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Nro. Identificación'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nombre1',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nombre2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=35, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='tipo_ter',
            field=models.CharField(blank=True, choices=[('Paciente', 'Paciente'), ('Hospital', 'Hospital'), ('Medico', 'Medico'), ('Pagador', 'Pagador')], default='', max_length=10, verbose_name='Tipo Tercero'),
        ),
        migrations.AlterField(
            model_name='tipocirugia',
            name='idcirugia',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Código Cirugía'),
        ),
        migrations.AlterField(
            model_name='tipoidentificacion',
            name='idtipoidentifica',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipoinjerto',
            name='caracteristicas',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='tipoinjerto',
            name='idtipoinjerto',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Código Tipo de Injerto'),
        ),
    ]
