# Generated by Django 3.0.4 on 2020-05-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20200502_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudaddireccion',
            name='idciudad',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Código Ciudad'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='direccion_envio',
            field=models.CharField(max_length=100, verbose_name='Dirección de Envio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono_envio',
            field=models.CharField(max_length=35, verbose_name='Teléfono de Envio'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='apel1',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='apel2',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='ciudad_direccion',
            field=models.ForeignKey(blank=True, default='', max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.CiudadDireccion', verbose_name='Ciudad Direcciòn'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='identificacion',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Nro. Identificación'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nombre1',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nombre2',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=35, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='tipo_ter',
            field=models.CharField(blank=True, choices=[('Paciente', 'Paciente'), ('Hospital', 'Hospital'), ('Medico', 'Medico'), ('Pagador', 'Pagador')], default='', max_length=10, null=True, verbose_name='Tipo Tercero'),
        ),
        migrations.AlterField(
            model_name='tipocirugia',
            name='idcirugia',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Código Cirugía'),
        ),
    ]
