# Generated by Django 3.0.4 on 2020-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_auto_20200502_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='idciudad',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Código Ciudad'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='iddepartamento',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Código Departamento'),
        ),
        migrations.AlterField(
            model_name='eps',
            name='ideps',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='idespecial',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Código Especialidad'),
        ),
        migrations.AlterField(
            model_name='especialidadinjerto',
            name='idespecial',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Código Especialidad'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idgrupo',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Código Grupo'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='idpais',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Código País'),
        ),
        migrations.AlterField(
            model_name='plansalud',
            name='idplan',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Código Plan'),
        ),
        migrations.AlterField(
            model_name='tipoidentificacion',
            name='idtipoidentifica',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipoinjerto',
            name='caracteristicas',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='tipoinjerto',
            name='idtipoinjerto',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Código Tipo de Injerto'),
        ),
    ]
