# Generated by Django 3.0.4 on 2020-05-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_auto_20200502_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='idespecial',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Código Especialidad'),
        ),
        migrations.AlterField(
            model_name='especialidadinjerto',
            name='idespecial',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Código Especialidad'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idgrupo',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Código Grupo'),
        ),
        migrations.AlterField(
            model_name='tipoinjerto',
            name='caracteristicas',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='tipoinjerto',
            name='idtipoinjerto',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Código Tipo de Injerto'),
        ),
    ]
