# Generated by Django 3.0.4 on 2020-05-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_auto_20200502_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='id_recibe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Identificación Recibe'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_recibe',
            field=models.CharField(blank=True, max_length=35, verbose_name='Nombre Recibe'),
        ),
    ]
