# Generated by Django 3.0.4 on 2020-06-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_auto_20200521_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudaddireccion',
            name='departamento',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='pedidos.Departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='ciudaddireccion',
            name='pais',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pais', verbose_name='País'),
        ),
    ]
