# Generated by Django 3.0.4 on 2020-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_auto_20200602_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
