# Generated by Django 3.0.4 on 2020-07-08 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_solicitud_cerrada'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tipoinjerto',
            managers=[
                ('injertos_activos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tercero',
            name='ciudad',
            field=models.ForeignKey(blank=True, default='1111', max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Ciudad', verbose_name='Ciudad Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='ciudad_direccion',
            field=models.ForeignKey(blank=True, default='1112', max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.CiudadDireccion', verbose_name='Ciudad Direcciòn'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='especialidad',
            field=models.ForeignKey(blank=True, default='31', max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Especialidad', verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default='01/01/1900', null=True, verbose_name='Fecha de Nacimiento DD/MM/AAAA'),
        ),
    ]
