# Generated by Django 3.0.4 on 2020-07-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_auto_20200708_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='ciudad',
            field=models.ForeignKey(blank=True, default=1111, max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Ciudad', verbose_name='Ciudad Nacimiento'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='eps',
            field=models.ForeignKey(blank=True, default=1, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Eps', verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='especialidad',
            field=models.ForeignKey(blank=True, default=31, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Especialidad', verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='plan_salud',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.PlanSalud', verbose_name='Plan Salud'),
        ),
    ]
