# Generated by Django 3.0.4 on 2020-07-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_auto_20200708_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='ciudad_envio',
            field=models.ForeignKey(blank=True, default='', max_length=5, on_delete=django.db.models.deletion.CASCADE, to='pedidos.CiudadDireccion', verbose_name='Ciudad Envío'),
        ),
    ]
