# Generated by Django 3.0.4 on 2020-07-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_auto_20200708_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='ciudad_envio',
            field=models.ForeignKey(default='99999', on_delete=django.db.models.deletion.CASCADE, to='pedidos.CiudadDireccion', verbose_name='Ciudad Envío'),
        ),
    ]
