# Generated by Django 3.0.4 on 2020-05-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Injertos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('proceso', models.CharField(blank=True, default='', max_length=40, verbose_name='Características')),
                ('uso_qx', models.CharField(blank=True, default='', max_length=2000, verbose_name='Características')),
                ('foto', models.ImageField(blank=True, default='static/img/placeholder.jpg', null=True, upload_to='fotos_injertos', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Injerto',
                'verbose_name_plural': 'Injertos',
                'ordering': ['descripcion'],
            },
        ),
    ]
