# Generated by Django 3.0.4 on 2020-03-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='ciudad_envio',
            field=models.ForeignKey(blank=True, default='', max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.CiudadDireccion', verbose_name='Ciudad Envío'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_cirugia',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Fecha Solicitud'),
        ),
    ]
