# Generated by Django 3.0.4 on 2020-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200328_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_cirugia',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Fecha Cirugía'),
        ),
    ]
