# Generated by Django 3.0.4 on 2020-03-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20200328_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadInjerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idespecial', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Código Especialidad')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Especialidad Injerto',
                'verbose_name_plural': 'Especialidades Injertos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.RemoveField(
            model_name='tipoinjerto',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='tipoinjerto',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.EspecialidadInjerto', verbose_name='Especialidad Injerto'),
        ),
    ]
