# Generated by Django 3.0.4 on 2020-03-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20200328_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocirugia',
            name='idcirugia',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Código Cirugía'),
        ),
    ]
