# Generated by Django 3.0.4 on 2020-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20200329_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddetalle',
            name='grupoinjerto',
        ),
        migrations.AlterField(
            model_name='tipoinjerto',
            name='foto',
            field=models.ImageField(blank=True, default='static/img/placeholder.jpg', null=True, upload_to='fotos_injertos', verbose_name='Foto'),
        ),
    ]
