# Generated by Django 3.0.4 on 2020-04-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_parametrossolicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrossolicitud',
            options={'verbose_name': 'Parametro Solicitud', 'verbose_name_plural': 'Parametros Solicitudes'},
        ),
        migrations.RemoveField(
            model_name='parametrossolicitud',
            name='solicitud',
        ),
    ]
