# Generated by Django 3.0.4 on 2020-04-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_parametrossolicitud_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Email'),
        ),
    ]
