# Generated by Django 3.0.4 on 2020-04-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_auto_20200401_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDetalleTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('valortotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('user', models.CharField(max_length=35, verbose_name='Usuario')),
                ('solicitud', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_detalle_temp', to='pedidos.Solicitud')),
                ('tipoinjerto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pedidos.TipoInjerto', verbose_name='Tipo de Injerto')),
            ],
            options={
                'verbose_name': 'Detalle Solicitud Temporal',
                'verbose_name_plural': 'Detalle Solicitudes Temporal',
                'ordering': ['solicitud'],
            },
        ),
    ]
