# Generated by Django 3.0.4 on 2020-06-17 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_auto_20200602_1639'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='loads/anexos')),
                ('idanexo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.TipoAnexo', verbose_name='Tipo Anexo')),
                ('idsolicitud', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Solicitud', verbose_name='Solicitud No.')),
            ],
        ),
    ]
